### ISSUE TITLE
Error during testing: [SEQPROV] RefBase file not found ()

### ISSUE THREAD

**Issue by 6C3C41** [Cibiv/NextGenMap#10]
I compiled with no errors, following instructions, and received this error when testing. Any help would be greatly appreciated!

`./ngm -r dh10b_ecoli.fasta -1 dh10b_ecoli.fasta_1.fastq -2  dh10b_ecoli.fasta_2.fastq -o test.sam`

> [MAIN] NextGenMap 0.4.12
> [MAIN] Startup : x64 (build Mar 15 2016 09:42:53)
> [MAIN] Starting time: 2016-03-15.09:58:17
> [CONFIG] Parameter:  --affine 0 --argos_min_score 0 --block_multiplier 2 --bs_cutoff 6 --bs_mapping 0 --cpu_threads 1 --dualstrand 1 --fast_pairing 0 --format 1 --gap_extend_penalty 5 --gap_read_penalty 20 --gap_ref_penalty 20 --hard_clip 0 --keep_tags 0 --kmer 13 --kmer_min 0 --kmer_skip 2 --match_bonus 10 --match_bonus_tc 4 --match_bonus_tt 4 --max_cmrs 2147483647 --max_equal 1 --max_insert_size 1000 --min_identity 0.650000 --min_insert_size 0 --min_mq 0 --min_residues 0.500000 --min_score 0.000000 --mismatch_penalty 15 --mode 0 --no_progress 0 --no_unal 0 --ocl_threads 1 --output test.sam --overwrite 1 --pair_score_cutoff 0.900000 --paired 1 --parse_all 1 --pe_delimiter / --qry1 dh10b_ecoli.fasta_1.fastq --qry2 dh10b_ecoli.fasta_2.fastq --qry_count -1 --qry_start 0 --ref dh10b_ecoli.fasta --ref_mode -1 --silent_clip 0 --skip_mate_check 0 --skip_save 0 --step_count 4 --strata 0 --topn 1
> [STATS] Exporting stats at 0x8f60b000 (Key 0x730110db, ID 0x18001)
> [NGM] Opening for output (SAM):
> [NGM] NGM Core initialization
> [SEQPROV] Init sequence provider.
> [SEQPROV] RefBase file not found ()
> This error is fatal. Quitting...
> 

### GCC

> gcc (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010

### Ubuntu

> Distributor ID: Ubuntu
> Description:    Ubuntu 15.10
> Release:        15.10
> Codename:       

### GPU

> *-display:1
>        description: VGA compatible controller
>        product: GK104GL [GRID K520]
>        vendor: NVIDIA Corporation
>        physical id: 3
>        bus info: pci@0000:00:03.0
>        version: a1
>        width: 64 bits
>        clock: 33MHz
>        capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
>        configuration: driver=nvidia latency=0
>        resources: irq:28 memory:ea000000-eaffffff memory:c0000000-c7ffffff memory:e2000000-e3ffffff ioport:c100(size=128) memory:ef000000-ef07ffff
>   *-display:2
>        description: VGA compatible controller
>        product: GK104GL [GRID K520]
>        vendor: NVIDIA Corporation
>        physical id: 4
>        bus info: pci@0000:00:04.0
>        version: a1
>        width: 64 bits
>        clock: 33MHz
>        capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
>        configuration: driver=nvidia latency=0
>        resources: irq:32 memory:eb000000-ebffffff memory:c8000000-cfffffff memory:e4000000-e5ffffff ioport:c180(size=128) memory:ef080000-ef0fffff
>   *-display:3
>        description: VGA compatible controller
>        product: GK104GL [GRID K520]
>        vendor: NVIDIA Corporation
>        physical id: 5
>        bus info: pci@0000:00:05.0
>        version: a1
>        width: 64 bits
>        clock: 33MHz
>        capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
>        configuration: driver=nvidia latency=0
>        resources: irq:36 memory:ec000000-ecffffff memory:d0000000-d7ffffff memory:e6000000-e7ffffff ioport:c200(size=128) memory:ef100000-ef17ffff
>   *-display:4
>        description: VGA compatible controller
>        product: GK104GL [GRID K520]
>        vendor: NVIDIA Corporation
>        physical id: 6
>        bus info: pci@0000:00:06.0
>        version: a1
>        width: 64 bits
>        clock: 33MHz
>        capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
>        configuration: driver=nvidia latency=0
>        resources: irq:40 memory:ed000000-edffffff memory:d8000000-dfffffff memory:e8000000-e9ffffff ioport:c280(size=128) memory:ef180000-ef1fffff

**Comment by fritzsedlazeck** [comment]
Hi,
thanks for the message. Are you sure that the reference file is in the directory that you execute NextGenMap from? 
"[SEQPROV] RefBase file not found ()" 

Thanks
Fritz

**Comment by 6C3C41** [comment]
Yes, it certainly is. My first guess was to hardcode all paths, same error. Thank you!

`ls`

> opencl  dh10b_ecoli.fasta          dh10b_ecoli.fasta_2.fastq    ngm       ngm-core-debug  ngm-log          ngm-utils        oclTool
> ?       dh10b_ecoli.fasta_1.fastq  dh10b_ecoli.fasta.fastq.sam  ngm-core  ngm-debug       ngm-testseq.tgz  ngm-utils-debug

**Comment by 6C3C41** [comment]
I also checked pems, tried ngm-core directly

**Comment by philres** [comment]
Hi!

Thanks for the detailed bug report!

Could you please download (https://github.com/Cibiv/NextGenMap/archive/dev.zip) or checkout the most recent "dev" branch and see wether it works then?

Thanks,
Philipp

**Comment by 6C3C41** [comment]
Done. Works. Anything I can do to help you sort the difference?

Thanks a lot guys...fastest response in history.

Andrew
