### ISSUE TITLE
when I try to make following the installing Instructions，it occurs 2 errors:make[2]: *** [src/CMakeFiles/ngm-core.dir/ReadProvider.cpp.o] Error 1 137 make[1]: *** [src/CMakeFiles/ngm-core.dir/all] Error 2, how can I solve the problems? gcc version 4.1.2

### ISSUE THREAD

**Issue by SYSULongyan** [Cibiv/NextGenMap#12]

**Comment by SYSULongyan** [comment]
![image](https://cloud.githubusercontent.com/assets/13273622/17288220/7cc3e570-5806-11e6-862a-622ee7294838.png)

**Comment by fritzsedlazeck** [comment]
Hi,
from what we can see you have a very old gcc version. It would be the easiest if you could update it. 
Let us know if this resolves the problem.
Thanks
Fritz

**Comment by SYSULongyan** [comment]
Thanks for your reply, actually I want to install the software in the cluster system.It has installed many gcc versions to use, but the default version is gcc 4.8.2
when I input:
$gcc --version
it shows:
gcc (GCC) 4.8.2
but when I input:
$cmake .. &> cmake.txt
and check the cmake.txt, the first two lines show:
 -- The C compiler identification is GNU 4.1.2                                                                       
 -- The CXX compiler identification is GNU 4.1.2
No errors when cmake.

but when I make
$make &> make.txt
And I check make.txt, it occurs two errors as before I said. And the gcc version is still 4.1.2.
It seems that gcc is automatically changing to the old version.
Should I midify the CMakeLists.txt? how?
Thanks
LongYan

**Comment by philres** [comment]
Hi,

you can try overriding gcc/g++ when calling cmake:

```bash
cmake -DCMAKE_CXX_COMPILER=g++-4.8.2 -DCMAKE_C_COMPILER=gcc-4.8.2 ..
make
```

But you have to delete everything in the "build" folder before you do that. Otherwise it won't work.

If it worked, the cmake output should indicate the changed compiler:

```
-- The C compiler identification is GNU
-- The CXX compiler identification is GNU
-- Check for working C compiler: /usr/bin/gcc-4.6
-- Check for working C compiler: /usr/bin/gcc-4.6 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++-4.6
-- Check for working CXX compiler: /usr/bin/g++-4.6 -- works
```

Please let us know whether this fixed your problem.

Thanks,
Philipp

**Comment by SYSULongyan** [comment]
Thanks a lot, it works.
Thank you,
LongYan
