### ISSUE TITLE
Run issue

### ISSUE THREAD

**Issue by SYSULongyan** [Cibiv/NextGenMap#13]
#Dear developers,
when I try to run NGM,
$./ngm
it showed that 
/parastor/users/lnszyd/longyan/NGP/N_test/NextGenMap-0.5.0/bin/ngm-0.5.0/ngm-core: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.11' not found (required by /parastor/users/lnszyd/longyan/NGP/N_test/NextGenMap-0.5.0/bin/ngm-0.5.0/ngm-core)
/parastor/users/lnszyd/longyan/NGP/N_test/NextGenMap-0.5.0/bin/ngm-0.5.0/ngm-core: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.9' not found (required by /parastor/users/lnszyd/longyan/NGP/N_test/NextGenMap-0.5.0/bin/ngm-0.5.0/ngm-core)
when I type:
$strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX
it doesn't contain GLIBCXX_3.4.9 or GLIBCXX_3.4.11, because the /usr/lib64/libstdc++.so.6 is the very old version lib
Cuz I want to use NGM in school's cluster system(GPU platform), I don't have root access to update libstdc++.so.6

And when I type:
$ldd ./ngm-core
it showed(the fifth line):
 ./ngm-core: /usr/lib64/libOpenCL.so.1: no version information available (required by ./ngm-core)
./ngm-core: /usr/lib64/libOpenCL.so.1: no version information available (required by ./ngm-core)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x000000357d800000)
	libOpenCL.so.1 => /usr/lib64/libOpenCL.so.1 (0x00002b5c4f10e000)
	**libstdc++.so.6 => /parastor/users/lnszyd/cy_test/softwares/gcc-4.8.2/lib64/libstdc++.so.6 (0x00002b5c4f314000)**
	libm.so.6 => /lib64/libm.so.6 (0x000000357d000000)
	libgcc_s.so.1 => /parastor/users/lnszyd/cy_test/softwares/gcc-4.8.2/lib64/libgcc_s.so.1 (0x00002b5c4f629000)
	libc.so.6 => /lib64/libc.so.6 (0x000000357cc00000)
	/lib64/ld-linux-x86-64.so.2 (0x000000357c800000)
	libdl.so.2 => /lib64/libdl.so.2 (0x000000357d400000)

And it's no use to
$export LD_LIBRARY_PATH=/the_path_to_new_version_lib/
How can I solve this problem.
Thx!

**Comment by SYSULongyan** [comment]
I solved the problem. when I cmake, I add  -DCMAKE_EXE_LINKER_FLAGS='-Wl,-rpath,/path_to new_lib'
Anyway, thx.

**Comment by fritzsedlazeck** [comment]
Thanks for solving this :).
Cheers
Fritz
