### ISSUE TITLE
ngm quits on OpenCL error

### ISSUE THREAD

**Issue by lucaptra** [Cibiv/NextGenMap#14]
I installed the program on a Macbook Pro OS X 10.8.5 with Intel Core i7 and Intel HD Graphics 4000 (so OpenCL 1.2). After successfully building ngm with the MacPorts version of gcc 4.9, the program runs through a few of the initial processes before terminating with the following error: "[OPENCL] Couldn't get number of OpenCl devices. Error: 
Error: Device not found. (-1)".

Any ideas on what is causing this problem and how to fix it would be greatly appreciated.

Thanks,
Lucy

**Comment by Acanthodasha** [comment]
Same

**Comment by fritzsedlazeck** [comment]
yeah we never tested or developed it on a Mac.. Lots of the drivers for the gpu are different etc... 
Sorry
Fritz
