### ISSUE TITLE
Old use of PERL license 1.0

### ISSUE THREAD

**Issue by doctormo** [Cibiv/NextGenMap#15]
The old Artistic License 1.0 is considered non-free (i.e. not open source) and shouldn't be used any more. Instead the Artistic License 2.0 or a dual AL/GPL license can be used. These provide the most amount of compatibility with other open source projects.

More details available here: https://en.wikipedia.org/wiki/Artistic_License

Also of concern is the inclusion of 'All rights reserved' in Templatized C++ Command Line Parser Library. The original code on sourceforge is a permissive license, but perhaps Daniel Aarno's modifications made it proprietary. Either way, it's inclusion is copyright infringement or a mistake in the license file (I hope it's the later)

Considering I'm not a lawyer and this project uses a couple of different code sources with their own licenses. I recommend contacting the Freedom Software Law Center https://www.softwarefreedom.org/about/contact/ they offer open source projects legal advice in cases such as this.

**Comment by philres** [comment]
Thanks for your feedback, we will switch to the MIT licence with our next release.

**Comment by doctormo** [comment]
Thanks!
