### ISSUE TITLE
Documentation for heuristic gap model

### ISSUE THREAD

**Issue by evolvedmicrobe** [Cibiv/NextGenMap#16]
Apologies if this already exists somewhere, but I was not able to find it after scanning the original publication, the supplements and associated references.

I was curious if there was any documentation somewhere for the "heuristic non-affine gap model" described in this poster about the mapper: 

http://schatzlab.cshl.edu/publications/posters/2015/2015.GI.NextGenMap-LR.pdf

Many of us heard word that non-affine penalties increased the complexity of the algorithm (e.g. https://en.wikipedia.org/wiki/Gap_penalty#Comparing_time_complexities), and so I was curious what the heuristic was and how it was employed.  Are there any good sources? This might also be a good candidate question to be added to the FAQ (https://github.com/Cibiv/NextGenMap/wiki/FAQ)?

Thanks for making this publicly available and for the great work!

Warm wishes,
Nigel

**Comment by fritzsedlazeck** [comment]
Hey Nigel,
thanks for your question. We are currently writing up the manuscript for NGM-LR and Sniffles and we will include a description in there. 

Thanks
Fritz
