### ISSUE TITLE
Supplementary Data Missing

### ISSUE THREAD

**Issue by reedacartwright** [Cibiv/NextGenMap#20]
The links to the supplementary data are not working on the Bioinformatics website.

https://academic.oup.com/bioinformatics/article-lookup/doi/10.1093/bioinformatics/btt468

Is the data accessible from anywhere else?

**Comment by fritzsedlazeck** [comment]
Hey thanks for letting us know. I have to write them to see if we can change that. 

I just sent it to you via email.
