### ISSUE TITLE
Provide example data to test that config is OK ?

### ISSUE THREAD

**Issue by sam217pa** [Cibiv/NextGenMap#21]
Hi, 

Thanks for your work on NGM, it seems like a great tool to use !
I tried it on my amplicon sequencing data and could not get it to work though. At this point I can't exclude that it comes from a peculiarity of my data, if something went wrong during the installation process or anything else.

Would it be possible for you to provide a sample dataset (raw fastq reads and its corresponding reference genome) that you use to test ngm for example ?

(A bacterial genome sequencing project would be great: it is small enough that the alignment can be run on a single computer in less than a minute (indexing a 3.6Mb genome with NGM took less than 10s on my setup).)

Thanks !

**Comment by fritzsedlazeck** [comment]
Hi,
let us know how it goes. It is a bit hidden in the wiki:

wget http://www.cibiv.at/~philipp_/files/ngm-testseq.tgz
tar xvzf ngm-testseq.tgz

Cheers
Fritz

**Comment by sam217pa** [comment]
Thanks ! Hadn't spotted it in the Docker related section.

Everything worked fine, could generate the alignment .sam file in 10 sec (no GPU) !

(I think my problem is related to the crazy depth I have. It is an amplicon sequencing experiment, so all 80k reads map to the same reference region, which confuses most alignment and variant calling tools …)

As for the sample data I would suggest that you make it more visible :)
Great work on NGM though, installation was really easy and documentation does quite the job.

Thanks
