### ISSUE TITLE
"Broken paired" interleaved FASTQ input

### ISSUE THREAD

**Issue by kdmurray91** [Cibiv/NextGenMap#23]
Hi,

Thanks for releasing nextgenmap, it's a great tool.

We're in the process of switching from using BWA to nextgenmap for read alignment. One sticking point at the moment is the support for "broken paired" read input. This is like interleaved format, except that reads whose pairs have been lost during trimming do not appear, e.g.:

```
@frag1/1
ACGT
+
IIIII
@frag1/2
CAGT
+
IIIII
@frag2/1
ACGT
+
IIIII
@frag3/1
ACGT
+
IIIII
@frag3/2
CAGT
+
IIIII
```

BWA mem is able to handle this format when given the `-p` flag. It does so by checking the read ids and treating reads that come  with identical (before the `/{1,2}`) read ids as a pair, and the rest as single end.

I notice that I get an error while using this format with nextgenmap that the read ids do not match. How difficult would it be to write a command line flag that allows ngm to parse this format? Perhaps `--paired` with `--qry` could trigger this behaviour? Our current work-around is to add fake reads consisting of a single `N` to ensure every single read is correctly paired. I guess it could also be posible to implement this behaviour by filtering out such reads when writing the SAM?

Thanks,
Kevin

**Comment by fritzsedlazeck** [comment]
Hi,
what we are usually doing is to use ngm-utils interleave to separate paired end and single end reads. Map the paired end and single end independent of each other and merge them using samtools after the mapping. 

Let me know if that would work for you.
Thanks
Fritz

**Comment by kdmurray91** [comment]
Hi Fritz,

That is similar to our current solution, however this signficantly complicates the workflow, and means that the intermediate files must be written to disk. This is not optimal, especially with very large datasets.

I've atttempted an initial implementation of this feature, and will now create a PR. It would be wonderful if you could review and consider including this feature.

**Comment by philres** [comment]
Hi Kevin,

thank you very much for the pull request. I'll have a look at it as soon as possible!

Thanks,
Philipp

**Comment by philres** [comment]
Hi Kevin,

sorry for the delay! I have merged your pull request into the main branch, fixed one small issue and added the command line parameter "--broken-pairs".

Using "-q read.fq -p --broken-pairs" should work now with your files.

Thanks again for the pull request!

Philipp

**Comment by kdmurray91** [comment]
Thanks very much @philres, I'll test this out today.

Cheers,
Kevin

**Comment by kdmurray91** [comment]
@philres would it be possible for you to tag a release on github for 0.5.5? Our cluster management system needs tagged releases unfortunately.

**Comment by philres** [comment]
Yes sure. I'm traveling right now but I'll try doing it tomorrow or on
Sunday!

**Comment by kdmurray91** [comment]
Awesome, thanks! It would be great if you could cut the release such that it includes #28 


Safe travels,
K

**Comment by philres** [comment]
Release 0.5.5 is up and should include #28 as well.

https://github.com/Cibiv/NextGenMap/releases/tag/v0.5.5

Please let me know if something does not work!

Thanks,
Philipp

**Comment by kdmurray91** [comment]
All compiled and working, thanks heaps!

**Comment by philres** [comment]
Great. Thanks for letting me know!
