### ISSUE TITLE
Error message received while installing 

### ISSUE THREAD

**Issue by amrita1983** [Cibiv/NextGenMap#25]
CMake Error at CMakeLists.txt:28 (message):
  The compiler /usr/bin/c++ has no C++11 support.  Please use a different C++
  compiler.

-- Configuring incomplete, errors occurred!
See also "/data/results/Dr_Ashwin/SVfinder_SV_analysis/ngmlr-master/ngmlr-master/build/CMakeFiles/CMakeOutput.log".
See also "/data/results/Dr_Ashwin/SVfinder_SV_analysis/ngmlr-master/ngmlr-master/build/CMakeFiles/CMakeError.log".

Please help me to get it installed correctly

**Comment by fritzsedlazeck** [comment]
Hi please check if your C++ compiler is up to date. For example: gcc --version.

the error message says basically that your C++ compiler is outdated. The easiest way to get around this is probably looking at bioconda if you dont have root permissions on the PC. Or you can ask a sysadmin if the PC/cluster has one. 

Let me know if that helps.
Thanks
Fritz

**Comment by amrita1983** [comment]
Hi, Thank you for the reply, I have already informed sysadmin on this after getting the message, but they are not confident and expert enough to update the compiler and I don't have the root permission.

Is there any other option is there through which we can install the software in our local machine and run..

Please reply its urgent I have to align some urgent Nanopore (1D) data using the tool.
Please help.
Thanks
Amrita

**Comment by fritzsedlazeck** [comment]
Hi Amrita,
you are in the wrong repository. Check out NGMLR  for nanopore: https://github.com/philres/ngmlr

You can try to set up bioconda: https://bioconda.github.io/
you dont need root permissions for that.

and once this is done you can just type:
conda install ngmlr

and it should get installed.

**Comment by amrita1983** [comment]
Oh, Ok, Thanks a lot for the information.
I will then try this and will update once successful.
Thank you for the help.

**Comment by amrita1983** [comment]
Hi,

Thank you for the help, this time ngmlr worked fine as per your information I have installed through Bioconda. 
I have to run sniffles now for SV calls, so do I have to run it on sorted bam, I have generated  sam file form the ngmlr.
One more question I have, do you know any tool to do chromosome break point mapping. Basically I am interested to find the chimeric reads and the break points between two chromosomes.
If you have any idea of this please help me. 
I have nanopore read (1D) to do that.

**Comment by fritzsedlazeck** [comment]
Hi,
what exactly do you mean? Do you mean that e.g. two parts of a read is mapping to two chromosomes and you want to find the breakpoints? That is what Sniffles is doing.

**Comment by amrita1983** [comment]
Hi,
Yes you are absolutely right, I want to identify the breakpoints, the same way you have given the e.g. I have used Sniffles with default parameters, but that is not capturing the desired position of my read in the targeted chromosome, and I am not getting how to change the parameters, the documentation I have read is only mentioning that you have to change the parameters but nothing mentioned.
the command I have used :
sniffles -m test.sorted.bam -v test_sample.vcf"
please help.

**Comment by fritzsedlazeck** [comment]
Hi.
Please be aware that this is for reporting bugs and its the wrong program.
You need to check the parameters for sniffles (e.g. -s) and probably your coverage that you actually have. Furthermore, look at your data with e.g. IGV. 
Best
Fritz
