### ISSUE TITLE
Build error using Clang 5.0.0

### ISSUE THREAD

**Issue by zmertens** [Cibiv/NextGenMap#27]
I encountered this CMake build error using the following commands:
`cmake -G"Ninja" -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release ../..`

```cmake
../../src/ReadProvider.cpp:480:34: error: ordered comparison between pointer and zero ('char *' and 'int')
        while (gzgets(fp, buffer, 1000) > 0 && buffer[0] == '@') {
....
../../utils/paired/interleave-pairs.cpp:62:34: error: ordered comparison between pointer and zero ('char *' and 'int')
        while (gzgets(fp, buffer, 1000) > 0 && buffer[0] == '@') {
```
I just needed to remove the `> 0` comparison to get it to build and compile. 
I checked GNU g++ compiler and it works without the change.

**Comment by philres** [comment]
Thanks for reporting this.

I'll change it with the next release.
