### ISSUE TITLE
Not able to view sam file ?

### ISSUE THREAD

**Issue by pinninti19** [Cibiv/NextGenMap#42]
Hi,
After performing alignment, not able to view **sam file.** whether header is missing in sam file? . How to sort it out ?
Aligner - NextGenMap
Illumina human dataset- SRR3440456 (14.14 GB)
Readlength - 126bp
ref -hg38.fa (3.1Gb)

# CMD#
./ngm -r Ref/hg38.fa -1 /data/R1q20.fastq -2 /data/R2q20.fastq -t 10 -o /data/NextGenMap-0.5.0/SRR2962693.ngm.sam 

### Cant view Samfile ###
samtools view -H SRR2962693.ngm.sam
[E::hts_hopen] Failed to open file SRR2962693.ngm.sam
[E::hts_open_format] Failed to open file SRR2962693.ngm.sam
samtools view: failed to open "SRR2962693.ngm.sam" for reading: Exec format error

thanks

**Comment by fritzsedlazeck** [comment]
Can you provide the command line output of ngm?

Plus maybe a head -n 20 SRR2962693.ngm.sam

Thanks
Fritz

**Comment by pinninti19** [comment]
HI,
At first time I generated a truncated file, I rerun the program I'm able to
view the sam file. No Issues.

Thanks!
