### ISSUE TITLE
Question about indexing the reference genome

### ISSUE THREAD

**Issue by jullee** [Cibiv/NextGenMap#43]
Hi I see that NGM has its own method for indexing the reference genome but I'm wondering if the reference could also be indexed ahead of time using other tools (samtools faidx)? What are the consequences of indexing the reference with samtools instead of NGM?  Thanks!

**Comment by fritzsedlazeck** [comment]
Hi you need to index the reference with ngm. Otherwise this does not work. Many programs index the reference differently. To just index the reference you can run ngm -r your.fa
Cheers
Fritz

**Comment by jullee** [comment]
Thank for this answer. And just to be clear, upon running ngm with the reference and fastq files input as input, the program automatically indexes the reference in this way?

**Comment by fritzsedlazeck** [comment]
Yes it does. You can just index or do the index during the run. Also you can decide if you want to store the index or not.
Cheers
Fritz
