### ISSUE TITLE
Now packaged in Homebrew Science

### ISSUE THREAD

**Issue by tseemann** [Cibiv/NextGenMap#46]
```
brew install brewsci/bio/nextgenmap
```

**Comment by philres** [comment]
Hi Torsten,

thanks a lot that's great. I'll add/change `--version` and `--help`. Haven't had much time lately to look at the issues here, but I'll try to find some.

Thanks,
Philipp

**Comment by tseemann** [comment]
I hadn't heard about NGM until Mike Schatz mentioned he uses it on Twitter.
