### ISSUE TITLE
Massive discrepency between proper pair counts between NGM and bwa

### ISSUE THREAD

**Issue by mbhall88** [Cibiv/NextGenMap#47]
I was wondering if you could provide some insight into why there would be such a massive discrepancy in how many proper pairs `ngm` finds when compared to `bwa`. I'm not insinuating that one is wrong and the other is right, just wanting to get an idea of why they would be so different.  
Here is the `samtools flagstat` output for the same reads mapped to the same reference using:  

### ngm
```
3382756 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
3211477 + 0 mapped (94.94% : N/A)
3382756 + 0 paired in sequencing
1691378 + 0 read1
1691378 + 0 read2
######################################
456738 + 0 properly paired (13.50% : N/A)
######################################
3201086 + 0 with itself and mate mapped
10391 + 0 singletons (0.31% : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```

### bwa mem
```
3383677 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
921 + 0 supplementary
0 + 0 duplicates
3213327 + 0 mapped (94.97% : N/A)
3382756 + 0 paired in sequencing
1691378 + 0 read1
1691378 + 0 read2
######################################
3148218 + 0 properly paired (93.07% : N/A)
######################################
3202742 + 0 with itself and mate mapped
9664 + 0 singletons (0.29% : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```

**Comment by fritzsedlazeck** [comment]
Hi Michael,
as far as I am aware this is mainly because the defined insert size. You see ngm and bwa mem have different values/thresholds on how to define the insert size. NGM uses a fix value (as far as I remember, but @philres  might correct me) while bwa adjusts it based on what he sees from the input. 

Were these standard pairs or some longer spanning reads?
I hope that helps. 
Fritz

**Comment by mbhall88** [comment]
Ah I see. They were standard pairs.
