### ISSUE TITLE
NextGenMap for bisulfite data and methylation calling

### ISSUE THREAD

**Issue by ChemaMD** [Cibiv/NextGenMap#52]
Dear @fritzsedlazeck ,

My lab is using NextGenMap quite extensively, as it performs quite well with the highly polymorphic datasets we have (transcriptomic and epigenomic data from pooled wild populations). We are encountering however several issues when using NGM with bisulfite data, in particular with the format of the SAM/BAM file generated and its compatibility with downstream mainstream methylation callers (e.g. CGmaptools). The way we are calling NGM to map our reads is: 

`ngm --paired --bam -r <<genome>> -1 <<read1>>.fastq -2 <<read2>>.fastq -o <<output>>.bam -t 4 --no-unal --bs-mapping`

 I have a couple of questions in this regard:

- How does the BAM headers and flags of the BAM generated by NGM relate to those generated by other aligners (perhaps more standard in methylation pipelines) such as bowtie2 or Bismark? It is not completely clear from the documentation, and while I see that NGM offers the opportunity to add/customise the format of the SAM/BAM output, it is something that I'm not very familiar with.
- Is there any methylation caller that would work directly with the NGM output? I see one is BiSS or BiS-SNP, but BiSS code is apparently not available.

Thank you for your help and for generating such a great piece of code!

Best,

Chema

**Comment by fritzsedlazeck** [comment]
Dear Chema,
thanks for reaching out. Its been a while since I worked on the bisulfite mapping code. Could you also try the sam output as I am not sure if the bam output was tested well for this mode.

Last time I used it was for this: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4413256/ 
where we used a script from bismark in the end to compute the mehtylion profile based on the mapped reads. 

Hope that helps
Thanks
Fritz

**Comment by ChemaMD** [comment]
Dear Fritz,

Thanks for your reply! Ok, I will re-run it keeping the SAM output. I have a question regarding these two options:

    -d/--pe-delimiter <char>      Character used in suffix that identifies mate 1
                               and 2. E.g. /1 and /2. This suffixes will be
                               removed to ensure proper SAM output
                               (default: /)
    --keep-tags                   Copy BAM/SAM tags present in input file to
                               output file (default: off)

Should I include `--keep-tags`? and what about the PE suffixes?

Cheers,

Chema

**Comment by fritzsedlazeck** [comment]
Its been a while, but I think they are only if you use a bam file as input.
I wouldn't 
Thanks
Fritz
